### ISSUE TITLE
useScriptGoogleRecaptcha is not a function starting from 1.0.0‑beta.2

### ISSUE THREAD

**Issue by Remi-ctv** [nuxt/scripts#612]
### 🐛 The bug

Hi,
I'm encountering an issue when using useScriptGoogleRecaptcha(...).
The function works correctly in version 1.0.0-beta.1, but starting from 1.0.0-beta.2 and still in 1.0.0-beta.3, it throws:
`useScriptGoogleRecaptcha(...) is not a function``

Thanks!

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-uvnxmkms

### 🌈 Expected behavior

useScriptGoogleRecaptcha() should be available as in version 1.0.0‑beta.1.
